Hello microverse project
Eugeneiyukhun/Hello_Microverse_Project pull request #1
Opened 2023-07-04 12:47 UTC by Eugeneiyukhun

- HTML is used to design the block of the website.
- CSS to style the layout of the Hello Microverse work
- Proper HTML syntax is applied
- The HTML and CSS linter errors were properly fixed

2023-07-04 13:06 UTC, Ofarouq310 requested changes
Hi @Eugeneiyukhun, ✋ 

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥈

![giphy](https://github.com/Eugeneiyukhun/Hello_Microverse_Project/assets/102612396/e872f9ce-47d7-4a23-9b04-9f9d085f80b4)

## Highlights
✅ No linter errors.
✅ Followed GitHub flow.
✅ Descriptive PR title & summary.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 13:06 UTC, Ofarouq310 commented on .gitignore
- [ ] Kindly note that your `test.md` file should be listed here too.

2023-07-04 13:06 UTC, Ofarouq310 commented on README.md
- [ ] Kindly refer back to that [main template](https://github.com/microverseinc/readme-template), and make sure to check the following:
  
  - The table of contents should be in your `README`.
  - Every section in the template should be visible in your `README` except for two, the `Live Demo` section if you still do not own a deployment link for it, and the `FAQ` section since it is an optional one. Every other section should be included and you have to customize it to your project.
  - Your project files should include a `LICENSE`, kindly watch this [tutorial](https://www.youtube.com/watch?v=8Dm7XXvtqXI) which will help you create one, please do not forget to choose the "MIT" license.
  - Remember that if you removed a section from your `README` file, you should delete it also from the `Table of contents, and vice versa.

2023-07-04 14:28 UTC, V-Blaze requested changes
## Hi @Eugeneiyukhun , 

# Almost there 🟡 

![1094a3e620ebea4cd6cf2d0aceaa8f52](https://user-images.githubusercontent.com/107632780/229645999-eb4dcb1d-5a0c-4bdd-a150-2ab5cee3f40d.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing some changes from the previous reviewers, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
-  Linters setup correctly✔
-  Correct GIthub flow💯 🥇 ✔

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-04 14:28 UTC, V-Blaze commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] You have done great so far, but there are still some changes you need to make before moving to the next milestone. :+1: 
- [ ] As the previous reviewer suggested, you need to use the Microverse readme template, you do not need to remove any section, all you are required to do is to remove the placeholder comments and then customize each section to match your project. This is an example of how a [professional-looking readme should be ](https://github.com/V-Blaze/news-hub/blob/dev/README.md). I'll suggest you look into this.
- [ ] The License link in your Readem leads to a 404 error page. I'll suggest you add the appropriate link to the license file.
- - Screenshot:
![Screenshot from 2023-07-04 15-11-00](https://github.com/Eugeneiyukhun/Hello_Microverse_Project/assets/107632780/d494201a-9ded-4900-889d-71b2a2849577)

2023-07-05 02:22 UTC, braincee approved these changes
Hi @Eugeneiyukhun 👋 , I am @braincee, your Code Reviewer.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![youre-approved-shirley-auto-group](https://user-images.githubusercontent.com/78104544/226852457-95ef4c1d-5d51-4f76-abd8-1fdc06b89e77.gif)

OPTIONAL CHANGES
---

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @braincee._

---

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-05 02:58 UTC, merged